name: MathInTheMiddle
version: 0.1
date: 2017-11-16
description: |
    Math-in-the-Middle functionality for GAP

authors:
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de/
    - name: Michael Torpey
      url: http://www-groups.mcs.st-andrews.ac.uk/~mct25/

maintainers:
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de/
    - name: Michael Torpey
      url: http://www-groups.mcs.st-andrews.ac.uk/~mct25/

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "json"
      version: ">= 1.1.0"
      url: "https://gap-packages.github.io/json/"
    - name: "io"
      version: ">= 4.5.0"
      url: "https://gap-packages.github.io/io"

www: https://markuspf.github.io/MathInTheMiddle/
readme: README.md
packageinfo: https://markuspf.github.io/MathInTheMiddle/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/markuspf/MathInTheMiddle/releases/download/v0.1/MathInTheMiddle-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>PT17</span>]   <b class='BibAuthor'>Pfeiffer, M. and Torpey, M.</b>,
     <i class='BibTitle'>MathInTheMiddle, Math-in-the-Middle functionality for GAP,
             Version 0.1</i>
     (<span class='BibYear'>2017</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://markuspf.github.io/MathInTheMiddle/">https://markuspf.github.io/MathInTheMiddle/</a></span>.
    </p>
    

bibtex: |
    @misc{ MathInTheMiddle0.1,
      author =           {Pfeiffer, M. and Torpey, M.},
      title =            {{MathInTheMiddle}, Math-in-the-Middle functionality for GAP, {V}ersion 0.1},
      month =            {Nov},
      year =             {2017},
      note =             {GAP package},
      howpublished =     {\href                {https://markuspf.github.io/MathInTheMiddle/}                {\texttt{https://markuspf.github.io/}\discretionary
                          {}{}{}\texttt{MathInTheMiddle/}}},
      printedkey =       {PT17}
    }

